# fishdrive — macOS menu-bar app. Generated by scripts/tap-update.py.
cask "fishdrive" do
  version "0.3.1"
  sha256 "b375679015d5b8853943914f27f29bd67b810c0ad2e32182f4dfb8b2dc868df0"

  url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/fishdrive_v#{version}_macos.zip"
  name "fishdrive"
  desc "Encrypted file offload to your own VPSes (menu-bar app)"
  homepage "https://github.com/1F47E/fishdrive"

  app "fishdrive.app"

  # Ad-hoc signed: clear the quarantine bit so Gatekeeper allows first launch.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/fishdrive.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Logs/fishdrive",
  ]
end
