# fishdrive — macOS menu-bar app. Generated by scripts/tap-update.py.
cask "fishdrive" do
  version "0.3.0"
  sha256 "094482bb778a8a2e38c9d171ee8c8666b7db7ea29921cdab82b9049af0068ec5"

  url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/fishdrive_v#{version}_macos.zip"
  name "fishdrive"
  desc "Encrypted file offload to your own VPSes (menu-bar app)"
  homepage "https://github.com/1F47E/fishdrive"

  app "fishdrive.app"

  # Ad-hoc signed: clear the quarantine bit so Gatekeeper allows first launch.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/fishdrive.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Logs/fishdrive",
  ]
end
