# fishdrive — macOS menu-bar app. Generated by scripts/tap-update.py.
cask "fishdrive" do
  version "0.2.0"
  sha256 "d69128d2b00658516a6786ce6d0d094b84d1092f4c3a9666fec5c8127d346157"

  url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/fishdrive_v#{version}_macos.zip"
  name "fishdrive"
  desc "Encrypted file offload to your own VPSes (menu-bar app)"
  homepage "https://github.com/1F47E/fishdrive"

  app "fishdrive.app"

  # Ad-hoc signed: clear the quarantine bit so Gatekeeper allows first launch.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/fishdrive.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Logs/fishdrive",
  ]
end
