# feeshd — fishdrive server (run on your VPS). Generated by scripts/tap-update.py.
class Feeshd < Formula
  desc "fishdrive storage server (master/replica, one binary)"
  homepage "https://github.com/1F47E/fishdrive"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/1F47E/fishdrive/releases/download/v0.1.0/feeshd_v0.1.0_darwin_arm64.tar.gz"
      sha256 "d014a5cb59a71967e0aa19d5bb51f9ee3e23f41a0f910a527483add30179229d"
    end
    on_intel do
      url "https://github.com/1F47E/fishdrive/releases/download/v0.1.0/feeshd_v0.1.0_darwin_amd64.tar.gz"
      sha256 "73985dd7951681a9067ec3abe0fac59654d5fc831e4ef827b8a6e92ea3a460a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/1F47E/fishdrive/releases/download/v0.1.0/feeshd_v0.1.0_linux_amd64.tar.gz"
      sha256 "f814460f39fe5329ba2886421b66384a1bdd965e868c1c523fcc2b16f6db6eb7"
    end
  end

  def install
    bin.install "feeshd"
  end

  test do
    assert_match "v0.1.0", shell_output("#{bin}/feeshd version")
  end
end
