# feeshd — fishdrive server (run on your VPS). Generated by scripts/tap-update.py.
class Feeshd < Formula
  desc "fishdrive storage server (master/replica, one binary)"
  homepage "https://github.com/1F47E/fishdrive"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/feeshd_v#{version}_darwin_arm64.tar.gz"
      sha256 "e72afcdf2239d21515496537cd903c3ecdc8184f8a64fff23967deced3c10c05"
    end
    on_intel do
      url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/feeshd_v#{version}_darwin_amd64.tar.gz"
      sha256 "5faab98636670bc584e6f47076476094f8e32d6daac07eeea6b1b56156bacec8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/feeshd_v#{version}_linux_amd64.tar.gz"
      sha256 "ccaefe7931c13da17ffd9d0ffa94abf6d2f286343152d1901ea63a2d763c7c45"
    end
  end

  def install
    bin.install "feeshd"
  end

  test do
    assert_match "v0.2.0", shell_output("#{bin}/feeshd version")
  end
end
