# fishctl — fishdrive CLI. Generated by scripts/tap-update.py; do not edit by hand.
class Fishctl < Formula
  desc "fishdrive CLI: encrypted file offload to your own VPSes"
  homepage "https://github.com/1F47E/fishdrive"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/fishctl_v#{version}_darwin_arm64.tar.gz"
      sha256 "9b258aac4f4c2f90edeb5ce4034d14d7e58e95005840680a7a4cd01817877a4f"
    end
    on_intel do
      url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/fishctl_v#{version}_darwin_amd64.tar.gz"
      sha256 "f4feba571940b728c12aa43232947da2effa0cc164b2d9a3b61658534d5952e3"
    end
  end

  def install
    bin.install "fishctl"
  end

  test do
    assert_match "v0.3.0", shell_output("#{bin}/fishctl --version")
  end
end
