# fishctl — fishdrive CLI. Generated by scripts/tap-update.py; do not edit by hand.
class Fishctl < Formula
  desc "fishdrive CLI: encrypted file offload to your own VPSes"
  homepage "https://github.com/1F47E/fishdrive"
  version "0.3.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/fishctl_v#{version}_darwin_arm64.tar.gz"
      sha256 "244aa3a7017eda546396eb4bce5572b17a6ddc6e9aa29a39867b915ad821e21d"
    end
    on_intel do
      url "https://github.com/1F47E/homebrew-fishdrive/releases/download/v#{version}/fishctl_v#{version}_darwin_amd64.tar.gz"
      sha256 "10443aa1105827637cd17a149a3b480d1b5e06aa943628131b26ff2577078107"
    end
  end

  def install
    bin.install "fishctl"
  end

  test do
    assert_match "v0.3.1", shell_output("#{bin}/fishctl --version")
  end
end
